name: Badger Docker Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  badger-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./Dockerfile
          tags: clarkteddyswap/teddy-badger:${{ github.sha }}-linux-amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: CACHE_BUST=${{ github.sha }}-linux-amd64
          platforms: linux/amd64

  badger-arm64:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: clarkteddyswap/teddy-swap-badger:${{ github.sha }}-linux-arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: CACHE_BUST=${{ github.sha }}-linux-arm64
          platforms: linux/arm64

  badger-keygen-amd64:
      runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./badger-keygen.Dockerfile
          tags: clarkteddyswap/teddy-badger-keygen:${{ github.sha }}-linux-amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: CACHE_BUST=${{ github.sha }}-linux-amd64
          platforms: linux/amd64

  badger-keygen-arm64:
      runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./badger-keygen.Dockerfile
          tags: clarkteddyswap/teddy-badger-keygen:${{ github.sha }}-linux-amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: CACHE_BUST=${{ github.sha }}-linux-amd64
          platforms: linux/arm64